"""
    OpenAPI SkyPort

    SkyPort server  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.job_to_submit import JobToSubmit


class TestJobToSubmit(unittest.TestCase):
    """JobToSubmit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJobToSubmit(self):
        """Test JobToSubmit"""
        # FIXME: construct object with mandatory attributes with example values
        # model = JobToSubmit()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
