"""
    OpenAPI SkyPort

    SkyPort server  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.default_api import DefaultApi  # noqa: E501


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_job(self):
        """Test case for add_job

        Submit a new job  # noqa: E501
        """
        pass

    def test_delete_pet(self):
        """Test case for delete_pet

        Cancels a job  # noqa: E501
        """
        pass

    def test_get_job_by_id(self):
        """Test case for get_job_by_id

        Find job by ID  # noqa: E501
        """
        pass

    def test_get_jobs(self):
        """Test case for get_jobs

        List all jobs  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
